# Generated by Django 6.0.7 on 2026-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "用户信息", "verbose_name_plural": "用户信息"},
        ),
    ]
