# Generated by Django 6.0.7 on 2026-08-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NiceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="售价"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "普通靓号"), (2, "高级靓号"), (3, "顶级靓号")],
                        verbose_name="靓号等级",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "可售"), (2, "已售出"), (3, "预留")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
            ],
            options={
                "verbose_name": "靓号",
                "verbose_name_plural": "靓号",
            },
        ),
    ]
