# Generated by Django 6.0.7 on 2026-08-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum_delete_nicenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prettynum",
            name="create_time",
        ),
    ]
