# Generated by Django 6.0.7 on 2026-08-19 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_remove_prettynum_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="prettynum",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="录入时间",
            ),
            preserve_default=False,
        ),
    ]
